name: location_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ">=3.38.0"
  sdk: ">=3.10.0"

dependencies:
  background_location: ^0.13.2
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
